### ISSUE TITLE
Just loading plottools overwrites the relational saving

### ISSUE THREAD

**Issue by saschuta** [bendalab/plottools#3]
When not loading plottools, relational saving is possible: 
      import matplotlib.pyplot as plt
      plt.plot([2,1],[2,1])
      plt.savefig('../results/test.png')
      plt.show()

Wheras when laoding plottools but not using it an error occurs:
      import matplotlib.pyplot as plt
      from plotstyle import plot_style, spines_params
      plt.plot([2,1],[2,1])
      plt.savefig('../results/test.png')
      plt.show()

See following link for detailed error message.
        ![SavefigChanges](https://user-images.githubusercontent.com/56550328/118254687-a7a5cb80-b4ab-11eb-90ae-e2aa95ace9d9.png)

The problem seems to occure in figure.py at lines 491-497 wehre due to the lines:
        if fname[0] in '.@':
            fname = os.path.splitext(os.path.basename(__main__.__file__))[0] + fname
the above relation saving is altered.

**Comment by janscience** [comment]
Ok, you are right. Relative pathes do not work, exactly because of the lines you pointed out.

I fixed it in janscience/plottools:
```py
if fname[0] in '.@' and '/' not in fname and os.path.sep not in fname:
    fname = basename + fname
```
and will push it to bendalab/plottools tonight.

**Comment by janscience** [comment]
Fixed and enhanced. Pure pathes get default name appended.
